### ISSUE TITLE
cannot compile/install on windows

### ISSUE THREAD

**Issue by ericpyle** [smihica/pyminizip#3]
Thank you so much for this wrapper. I've been able to use pip to install on ubuntu, but I haven't been able to get it to install on windows due to multiple compiler errors. 

I've tried to install the zlib library on windows (gnuwin32), but I'm not sure pyminizip/setup.py knows how to find the source files it needs from that library.

Here is one error log from Pycharm package installer:

Here's the error log:
Install packages failed: Error occurred when installing package pyminizip. 

The following command was executed:

packaging_tool.py install --build-dir C:\Users\Pylee\AppData\Local\Temp\pycharm-packaging2473906546786097704.tmp pyminizip

The error output of the command:

Downloading/unpacking pyminizip
  Running setup.py egg_info for package pyminizip

Installing collected packages: pyminizip
  Running setup.py install for pyminizip
    building 'pyminizip' extension
    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc "-ID:\Program Files (x86)\Python27\include" "-ID:\Program Files (x86)\Python27\PC" /Tcsrc/py_minizip.c /Fobuild\temp.win32-2.7\Release\src/py_minizip.obj
    py_minizip.c
    c:\users\pylee\appdata\local\temp\pycharm-packaging2473906546786097704.tmp\pyminizip\src\zip.h(43) : fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
    error: command '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe"' failed with exit status 2
    Complete output from command "D:\Program Files (x86)\Python27\python.exe" -c "import setuptools;**file**='C:\Users\Pylee\AppData\Local\Temp\pycharm-packaging2473906546786097704.tmp\pyminizip\setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record c:\users\pylee\appdata\local\temp\pip-d5vjjc-record\install-record.txt:
    running install

running build

running build_ext

building 'pyminizip' extension

creating build

creating build\temp.win32-2.7

creating build\temp.win32-2.7\Release

creating build\temp.win32-2.7\Release\src

C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc "-ID:\Program Files (x86)\Python27\include" "-ID:\Program Files (x86)\Python27\PC" /Tcsrc/py_minizip.c /Fobuild\temp.win32-2.7\Release\src/py_minizip.obj

py_minizip.c

c:\users\pylee\appdata\local\temp\pycharm-packaging2473906546786097704.tmp\pyminizip\src\zip.h(43) : fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory

error: command '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe"' failed with exit status 2

---

Command "D:\Program Files (x86)\Python27\python.exe" -c "import setuptools;**file**='C:\Users\Pylee\AppData\Local\Temp\pycharm-packaging2473906546786097704.tmp\pyminizip\setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record c:\users\pylee\appdata\local\temp\pip-d5vjjc-record\install-record.txt failed with error code 1 in C:\Users\Pylee\AppData\Local\Temp\pycharm-packaging2473906546786097704.tmp\pyminizip
Storing complete log in C:\Users\Pylee\AppData\Roaming\pip\pip.log

**Comment by subashpaudyal** [comment]
i am also facing the same problem.. any help please...

**Comment by KenV99** [comment]
Same here fails looking for zlib.h on windows.

**Comment by inbgche** [comment]
C:\Users\someone\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC

In my case, 
Here is the place which should be the libraries, and head files of zlib. 
http://www.zlib.net/

**Comment by hamza07-w** [comment]
why pip install pyminizip not work

**Comment by 1273082756** [comment]
me too
