### ISSUE TITLE
Pyminizip is not working with python 3.10.0

### ISSUE THREAD

**Issue by InsomniakD** [smihica/pyminizip#38]
Code which work with python 3.9.7 now don't work anymore in python 3.10.0 it always return an error an error which is this one : "expected arguments are compress_multiple([src], [srcpath], dst, pass, level)" but after a 100 hundred recheck everything is correct and work with the past version so I guess it's an issue with the latest python version.

**Comment by rdeterre** [comment]
As stated [here](https://bugs.python.org/issue40943), Python 3.10 broke support for `#` formats if `PY_SSIZE_T_CLEAN` is not defined.

@smihica, I should be able to send a pull request to fix this. Would you be open to reviewing it?

**Comment by smihica** [comment]
Supported: https://pypi.org/project/pyminizip/0.2.6/
