### ISSUE TITLE
encryption does not work with compress_multiple

### ISSUE THREAD

**Issue by pwwebdev** [smihica/pyminizip#5]
This works fine (it creates a password protected ZIP):

    pyminizip.compress('file1.docx', 'files.zip', 'password', 5)

But this doesn't (it creates a ZIP without password protection):

    pyminizip.compress_multiple(['file1.docx', 'file2.docx'], 'files.zip', 'password', 5)

**Comment by smihica** [comment]
What version of python are you using?
========== In my environment (macosx10.5, python3.4,zlib1.2.5) =============
Python 3.4.1 (default, May 19 2014, 13:10:29)
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyminizip
>>> pyminizip.compress_multiple(['COPYING.txt', 'MANIFEST.in'], 'files.zip', 'password', 5)
(env)~/code/pyminizip% ls
COPYING.txt        MANIFEST.in        README.txt         build              dist               env                files.zip          pyminizip.egg-info setup.py           src
(env)~/code/pyminizip% unzip files.zip
Archive:  files.zip
[files.zip] COPYING.txt password: (password)
replace COPYING.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace MANIFEST.in? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
(env)~/code/pyminizip%
===============================
It shows it works fine.

**Comment by pwwebdev** [comment]
Thanks for your quick reply.

Just tested it via the command line, and it's working for both Python 2.7 and Python 3.4. It's just not working in my script, which is weird because I do the exact same thing.

My script:
    
    to_zip = ['file1.html', 'file2.html']
    zip_path = '/tmp/files.zip'
    password = 's3cr3t'

    pyminizip.compress_multiple(to_zip, zip_path, 's3cr3t', 5) # with hardcoded pass it works

    pyminizip.compress_multiple(to_zip, zip_path, password, 5) # but this doesn't work

If I print the value of password it output the actual password, so it's not empty.

**Comment by smihica** [comment]
Hi ;), What version of Python are you using?
in my environment the script you wrote works fine.

    import pyminizip
    to_zip   = ['README.txt', 'MANIFEST.in']
    zip_path = '/tmp/files.zip'
    password = 's3cr3t'
    pyminizip.compress_multiple(to_zip, zip_path, password, 5)

in unzip command
    % unzip /tmp/files.zip
    Archive:  /tmp/files.zip
    [/tmp/files.zip] README.txt password: (EMPTY)
    skipping: README.txt              incorrect password
    skipping: MANIFEST.in             incorrect password

and Finder (like explorer in windows) works fine.

My environment is 
* pyminizip
    * 0.2.1
* zlib
    * 1.2.5
* Python
    * 3.4.1
* clang
    * Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
    * Target: x86_64-apple-darwin14.0.0
    * Thread model: posix

**Comment by pwwebdev** [comment]
I just updated pyminizip and now it works great, thanks!

**Comment by WhoYoung99** [comment]
Hi, I've encountered similar issues that compress_multiple does not work.

I am using Anaconda 3.5 and I was not able to install Pyminizip through

> pip install pyminizip

until I used this command: pip install git+https://github.com/andrewleech/pyminizip.git

Right now my compress function works fine but each time I execute compress_multiple my python crashes.
